dist: jammy
language: python

python:
- '3.9'

env:
  global:
  - secure: P/TYBbm9u30RLGrfNVNMm689qOqHJyBniwKITfgPiK3aujeGdT6Z1XDNPYPgwlWKE5kDPSf1ZA3CfTj2rwUOKWfKANeIH7BRLh0n02hIIwAZUiV1u8/5pQk84mDH5UAMtVOwsAbbRof+tvEjjfrr0EmCGnhcbVrXo7f9jIUXiJcRCMdjGgMmmoRu5WQhIyVfK7n+Qr9p84Vml999VFQkiPcmGTrJxbPE6tiTQoWRWc9ak3q/SEmUUP1F31B5FhF74C5B5DKZyq+oEWmzeXe5noleZ0vzW2uy3qupHh2bj+SZC/WcfNRPxMc49Pjc9sa65GgaLsTvww2nQX6Ioycgz7OOiIayJLFOKlvQ4Fahow1zjjUEI4/5y3bL7vhXFLEUn0dxvWXanmWLsO8cmM0NQ/AeXhrd2/2pblVtBVrimzkQydJANgyTCw2E/Wbvxnkxyc5GfttfRKgABJ/mLWNlKQ4RQNhAXmD7CqH9kd7T1+oyiuQTOj6Bu8wN5IsGuqv41k4aufyq5LN+4F9/ugex05NBGtGm6a9byAq7XjOzpvFWoki8kwVIoJie8gA74kUf05iAl0iQVqCMFPrxNyeH2cngZgfi+rs7KhnoJ9ZctqCDHIg75xPt9heskn2pw59VU1tcs1QOmNEynEMsusC/wA/WbBQrx9ppVovqjvCaozg=
  - secure: yJIyJjcQJBm4ejfhSjyO0iq65ZPAt1lXrtipa89MI+sZ45AG9AQ30ey4zUc1lsc94XHM+y+lR8V5Z/Ej2qMYg5NfDWN/3x1sawuqR3PNxgtgg6cGb+uARO0QUqNIUQf0dnNw1O8sYJfoCtQ4CPM8Ig7GX6pOdST2pPXNuikHZCDB8sgatr3921fhbi14mzMo7hMujOGLb//mZ2xfhzXaGIeJPSRfjBAdPxFKBt2rJpNlFRhTcPEL8BG7jflguXQ0bybK6zWC3DJN6iqGiarKXmJL8M7p393mfWruLaDSA05Gq/LioFnlS2XkLvoafaiAyumsBQuDCjpNy8RK+PDqIMDFAH0fJxpwrYIs8KAHSvnjQHE3JhQywkYJLCZhqCAn66j8VcYw0KkhyogIf4Mgl4naO4AqoULJTNKq/Pozx46jIRjHxH6LXQeZEPkfL/ybWNOPgHEHCu0PkZ4TMaTneF+MSNFXJHzi6ks81/scPsaSlvamzFlQwkKgT2tYufGoi/6rsagYuT+XoiNRacYYchnZ5agTU/SjLU63kebGS3sT2EA09Rh+p8JMD+plpp+rB60KWWstTBtjkWytrXqjewWsfSvSL99lzZafg0OkKP9ztz6HPrd5wZ+ysI4DHX5QZ6if0wzzlaZ+qKIh8PsvSbWxPrHzui9Fe9OXqvsm8gs=


install:
  - pip install --upgrade pip
  - sudo apt-get install libssl-dev --upgrade
  - pip install poetry
  - poetry --version
  - poetry install -vv

script:
  - poetry run pytest -vv tests
  
before_deploy:
- poetry config pypi-token.pypi $PYPI_API_TOKEN
- poetry build -f sdist

deploy:
  provider: script
  script: poetry publish -n -vv
  skip_cleanup: true
  on:
    tags: true
    repo: uc-cdis/datadictionary
    python: 3.9

after_deploy:
- pip install gen3git
- gen3git release
